#ifndef __INCLUDED_PPSEC__
#define __INCLUDED_PPSEC__
#ifdef __cplusplus
extern "C" {
#endif

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <sys/types.h>
#include "PPSecEasyPayClientAPI.h"
#include "PPSecEasyPayAdvClientAPI.h"
#include "PPSecEasyPayComm.h"
#include "PPSecEasyPayAdvComm.h"
/* Header for class com_tools_client */

#include <android/log.h>
#include <string.h>
#include <inttypes.h>
#include <sys/time.h>

#define LOG_TAG "dongnan###################"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)

static uint8_t secretKey[C_CONTEX_LEN];
/*
* Class:     cn_paypalm_easypay_protocol_VirgoClient
* Method:    encryptMsg
* Signature: ([BLjava/lang/String;)I
*/
jint encryptMsg(JNIEnv *env, jclass obj, jbyteArray jindata, jint jdatalen, jobject joutdata)
{
    int ret = -1;
    int packetlen;
    jmethodID mid;

    uint8_t *ctx = secretKey;
    if ( NULL == ctx ) {
        goto LEAVE1;
    }

    uint8_t *indata = (uint8_t *)(*env)->GetByteArrayElements( env, jindata, 0 );
    if ( NULL == indata ) {
        goto LEAVE2;
    }

    int datalen = jdatalen;
    if(datalen<0){
        goto LEAVE2;
    }

    jclass cls = (*env)->GetObjectClass(env, joutdata);
    if ( NULL == cls ) {
        goto LEAVE3;
    }
    LOGI("en%d",1);
    uint8_t *uintarray = (uint8_t*)malloc(datalen+PKT_HEADER_LEN);
    packetlen = datalen+PKT_HEADER_LEN;
    ret = packet_encode( ctx, indata, datalen, uintarray, &packetlen );
    FILE *fp = fopen("/sdcard/ppsec", "a+");
    fwrite(ctx, 1,C_CONTEX_LEN, fp);
    fclose(fp);
    LOGI("en%d",2);
    if(ret<0){
        goto LEAVE4;
    }
    LOGI("en%d",3);
    jbyteArray bytearray = (*env)->NewByteArray(env,packetlen);
    (*env)->SetByteArrayRegion(env,bytearray, 0, packetlen , (jbyte*)uintarray);
    LOGI("en%d",4);
    mid = (*env)->GetMethodID(env, cls, "setByteData", "([B)V");
    (*env)->CallVoidMethod(env, joutdata, mid, bytearray);

    mid = (*env)->GetMethodID(env, cls, "setDataLen", "(I)V");
    (*env)->CallVoidMethod(env, joutdata, mid, packetlen);
    LOGI("en%d",5);

LEAVE4:
    LOGI("en%d",6);
    free(uintarray);
LEAVE3:
    (*env)->DeleteLocalRef(env,cls);
LEAVE2:
    (*env)->ReleaseByteArrayElements( env, jindata,indata, 0 );
LEAVE1:
    return ret;
}

/*
* Class:     cn_paypalm_easypay_protocol_VirgoClient
* Method:    decryptMsg
* Signature: ([BLjava/lang/String;)I
*/
jint decryptMsg(JNIEnv *env, jclass obj, jbyteArray jindata, jint jdatalen, jobject joutdata)
{
    int ret = -1;
    int packetlen;
    jmethodID mid;

    uint8_t *ctx = secretKey;
    if ( NULL == ctx ) {
        goto LEAVE1;
    }

    uint8_t *indata = (uint8_t *)(*env)->GetByteArrayElements( env, jindata, 0 );
    if ( NULL == indata ) {
        goto LEAVE2;
    }
    LOGI("en%d",1);
    int datalen = jdatalen;
    if(datalen<=PKT_HEADER_LEN){
        goto LEAVE2;
    }
    LOGI("en%d",2);
    jclass cls = (*env)->GetObjectClass(env, joutdata);
    if ( NULL == cls ) {
        goto LEAVE3;
    }
    uint8_t *uintarray = (uint8_t*)malloc(datalen-PKT_HEADER_LEN);
    packetlen = datalen-PKT_HEADER_LEN;
    ret = packet_decode( ctx, indata, datalen, uintarray, &packetlen );
    FILE *fp = fopen("/sdcard/ppsec", "a+");
    fwrite(ctx, 1,C_CONTEX_LEN, fp);
    fclose(fp);
    if(ret<0){
        goto LEAVE4;
    }
    LOGI("en%d",3);
    jbyteArray bytearray = (*env)->NewByteArray(env,packetlen);
    (*env)->SetByteArrayRegion(env, bytearray, 0, packetlen , (jbyte*)uintarray);

    mid = (*env)->GetMethodID(env, cls, "setByteData", "([B)V");
    (*env)->CallVoidMethod(env, joutdata, mid, bytearray);

    mid = (*env)->GetMethodID(env, cls, "setDataLen", "(I)V");
    (*env)->CallVoidMethod(env, joutdata, mid, packetlen);

LEAVE4:
    LOGI("en%d",4);
    free(uintarray);
LEAVE3:
    (*env)->DeleteLocalRef(env,cls);
LEAVE2:
    LOGI("en%d",5);
    (*env)->ReleaseByteArrayElements( env, jindata,indata, 0 );
LEAVE1:
    LOGI("en%d",6);
    return ret;
}

/*
* Class:     cn_paypalm_easypay_protocol_VirgoClient
* Method:    doKeyExchangeA
* Signature: ([BLjava/lang/String;)I
*/
jint doKeyExchangeA(JNIEnv *env, jclass obj, jobject jpacket, jstring jrootPath, jint jappId)
{
    int ret = -1;
    uint8_t *ctx = secretKey;
    jmethodID mid;
    jclass cls;
    jbyteArray bytearray;

    if ( NULL == ctx ) {
        goto LEAVE1;
    }

    cls = (*env)->GetObjectClass(env, jpacket);
    if ( NULL == cls ) {
        goto LEAVE2;
    }

    const char *root_path = (*env)->GetStringUTFChars(env, jrootPath, 0);
    if(NULL == root_path){
        goto LEAVE3;
    }

    int app_id = jappId;

    ret = ppsec_easypay_init_client( ctx,root_path);
    if(ret < 0){
        goto LEAVE3;
    }

    uint8_t uintarray[RSA_BIT_NUM/8+PKT_HEADER_LEN];
    ret = exchange_key_client_A(ctx,app_id,uintarray);
    if(ret<0){
        goto LEAVE3;
    }

    FILE *fp = fopen("/sdcard/ppsec", "w+");
    fwrite(uintarray, 1, RSA_BIT_NUM/8+PKT_HEADER_LEN, fp);
    fclose(fp);
    /*
    int ptlen = 0;
    int len = RSA_BIT_NUM/8+PKT_HEADER_LEN;
    for (ptlen = 0;ptlen < len; ptlen++) {
        printf("0x0X", uintarray[ptlen]);
    }*/
    bytearray = (*env)->NewByteArray(env,RSA_BIT_NUM/8+PKT_HEADER_LEN);
    (*env)->SetByteArrayRegion(env,bytearray, 0,(RSA_BIT_NUM/8+PKT_HEADER_LEN) , (jbyte*)uintarray);

    mid = (*env)->GetMethodID(env, cls, "setByteData", "([B)V");
    (*env)->CallVoidMethod(env, jpacket, mid, bytearray );

    mid = (*env)->GetMethodID(env, cls, "setDataLen", "(I)V");
    (*env)->CallVoidMethod(env, jpacket, mid, RSA_BIT_NUM/8+PKT_HEADER_LEN );

LEAVE3:
    (*env)->ReleaseStringUTFChars(env, jrootPath, root_path);
LEAVE2:
    (*env)->DeleteLocalRef(env,cls);
LEAVE1:
    return ret;
}

/*
* Class:     cn_paypalm_easypay_protocol_VirgoClient
* Method:    doKeyExchangeB
* Signature: ([BLjava/lang/String;)I
*/
jint doKeyExchangeB(JNIEnv *env, jclass obj, jbyteArray jpacket)
{
    int ret = -1;
    int* packetlen;

    uint8_t *ctx = secretKey;
    if ( NULL == ctx ) {
        goto LEAVE1;
    }

    int packet_len = (int)(*env)->GetArrayLength(env, jpacket);
    if ( packet_len < PKT_HEADER_LEN+R2_SESSIONID_PKT_SIZE ) {
        return -1;
    }
    uint8_t *packet = (uint8_t *)(*env)->GetByteArrayElements( env, jpacket, 0 );
    if ( NULL == packet ) {
        goto LEAVE2;
    }

    ret = exchange_key_client_B( ctx,packet );

LEAVE2:
    (*env)->ReleaseByteArrayElements( env, jpacket, packet, 0 );
LEAVE1:
    return ret;
}

/*
* Class:     cn_paypalm_easypay_protocol_VirgoClient
* Method:    encryptSensitiveData
* Signature: ([BILjava/lang/String;)I
*/
jint encryptSensitiveData(JNIEnv *env, jclass obj, jint jdatatype, jbyteArray jindata, jint jdatalen, jobject joutdata)
{
    int ret = -1;
    int packetlen;
    jmethodID mid;
    jclass cls;

    uint8_t *ctx = secretKey;
    if ( NULL == ctx ) {
        goto LEAVE1;
    }

    int datatype = jdatatype;

    uint8_t *indata = (uint8_t *)(*env)->GetByteArrayElements( env, jindata, 0 );

    if ( NULL == indata ) {
        goto LEAVE2;
    }

    int datalen = jdatalen;

    cls = (*env)->GetObjectClass(env, joutdata);
    if ( NULL == cls ) {
        goto LEAVE3;
    }

    char *chararray = (char*)malloc(datalen+CCM_IV_LEN+CCM_TAG_LEN);
    packetlen = datalen+CCM_IV_LEN+CCM_TAG_LEN;
    ret = encrypt_sensitive_data_client( ctx, jdatatype, indata, datalen, chararray, &packetlen );
    if(ret<0){
        goto LEAVE4;
    }

    jbyteArray bytearray = (*env)->NewByteArray(env,packetlen);
    (*env)->SetByteArrayRegion(env,bytearray, 0, packetlen , (jbyte*)chararray);

    mid = (*env)->GetMethodID(env, cls, "setByteData", "([B)V");
    (*env)->CallVoidMethod(env, joutdata, mid, bytearray);

    mid = (*env)->GetMethodID(env, cls, "setDataLen", "(I)V");
    (*env)->CallVoidMethod(env, joutdata, mid, packetlen);

LEAVE4:
    free(chararray);
LEAVE3:
    (*env)->DeleteLocalRef(env,cls);
LEAVE2:
    (*env)->ReleaseByteArrayElements( env, jindata, indata, 0 );
LEAVE1:
    return ret;
}


jint digestSensitiveData(JNIEnv *env, jclass obj, jint jdatatype, jbyteArray jindata, jint jdatalen, jobject joutdata)
{
    int ret = -1;
        jmethodID mid;
        jclass cls;

        uint8_t *ctx = secretKey;
        if ( NULL == ctx ) {
            goto LEAVE1;
        }

        int datatype = jdatatype;

        uint8_t *indata = (uint8_t *)(*env)->GetByteArrayElements( env, jindata, 0 );

        if ( NULL == indata ) {
            goto LEAVE2;
        }

        int datalen = jdatalen;

        cls = (*env)->GetObjectClass(env, joutdata);
        if ( NULL == cls ) {
            goto LEAVE3;
        }

        char *chararray = (char*)malloc(HASH_LEN);

        ret = digest_sensitive_data( jdatatype, indata, datalen, chararray );
        if(ret<0){
            goto LEAVE4;
        }

        jbyteArray bytearray = (*env)->NewByteArray(env, HASH_LEN);
        (*env)->SetByteArrayRegion(env,bytearray, 0, HASH_LEN , (jbyte*)chararray);

        mid = (*env)->GetMethodID(env, cls, "setByteData", "([B)V");
        (*env)->CallVoidMethod(env, joutdata, mid, bytearray);

        mid = (*env)->GetMethodID(env, cls, "setDataLen", "(I)V");
        (*env)->CallVoidMethod(env, joutdata, mid, HASH_LEN);

    LEAVE4:
        free(chararray);
    LEAVE3:
        (*env)->DeleteLocalRef(env,cls);
    LEAVE2:
        (*env)->ReleaseByteArrayElements( env, jindata, indata, 0 );
    LEAVE1:
        return ret;
}


/*
* Class:     cn_paypalm_easypay_protocol_VirgoClient
* Method:    getServerUrl
* Signature: ([BLjava/lang/String;)I
*/
jstring getServerUrl(JNIEnv *env, jclass obj)
{
    // LOGI("hello, this is my number %d log message!", 1);
    //const char* pat = "http://192.168.22.84:8081/";


    //jclass strClass = (*env)->FindClass(env, "java/lang/String");
    // jmethodID ctorID = (*env)->GetMethodID(env, strClass, "<init>", "([BLjava/lang/String;)V");
    // jbyteArray bytes = (*env)->NewByteArray(env, strlen(pat));
    // (*env)->SetByteArrayRegion(env, bytes, 0, strlen(pat), (jbyte*)pat);
    // jstring encoding = (*env)->NewStringUTF(env, "utf-8");
    //LOGI("hello, this is my number %d log message!", 2);
    //return (jstring)(*env)->NewObject(env, strClass, ctorID, bytes, encoding);
    return (*env)->NewStringUTF(env,"http://192.168.22.84:8081/");
}

const static char* ppclasses[] = {
    "com/liuhong/app/NativeUtil"
};
const static JNINativeMethod mtCmd[] = {
    {"getServerUrl", "()Ljava/lang/String;", (jstring *) getServerUrl},
    {"encryptMsg", "([BILcom/liuhong/app/NativeData;)I", (jint *) encryptMsg},
    {"decryptMsg", "([BILcom/liuhong/app/NativeData;)I", (jint *) decryptMsg},
    {"encryptSensitiveData", "(I[BILcom/liuhong/app/NativeData;)I", (jint *) encryptSensitiveData},
    {"digestSensitiveData", "(I[BILcom/liuhong/app/NativeData;)I", (jint *) digestSensitiveData}
};
const static JNINativeMethod mtKeyExchange[] = {
    {"doKeyExchangeA", "(Lcom/liuhong/app/NativeData;Ljava/lang/String;I)I", (jint *) doKeyExchangeA},
    {"doKeyExchangeB", "([B)I", (jint *) doKeyExchangeB}
};

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved) {
    // Get JNI Env for all function calls
    JNIEnv* env;
    if ((*vm)->GetEnv(vm, (void **) &env, JNI_VERSION_1_6) != JNI_OK) {
        return -1;
    }
    
    jclass nativeCls = (*env)->FindClass(env, ppclasses[0]);
    if (nativeCls == NULL) {
        return -1;
    }

    // Register native method
    if ((*env)->RegisterNatives(env, nativeCls, mtCmd, sizeof(mtCmd) / sizeof(mtCmd[0]))) {
        return -1;
    }

    nativeCls = (*env)->FindClass(env, ppclasses[1]);
    if (nativeCls == NULL) {
        return -1;
    }

    // Register native method
    if ((*env)->RegisterNatives(env, nativeCls, mtKeyExchange, sizeof(mtKeyExchange) / sizeof(mtKeyExchange[0]))) {
        return -1;
    }

    return JNI_VERSION_1_6;
}

#ifdef __cplusplus
}
#endif
#endif
